# Generated by Django 4.1.3 on 2022-12-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='channel',
        ),
        migrations.AddField(
            model_name='product',
            name='channel',
            field=models.ManyToManyField(to='shop.channel'),
        ),
    ]
