# Generated by Django 4.1.3 on 2022-12-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.family'),
        ),
    ]
