# Generated by Django 4.1.3 on 2022-12-03 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_category_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='family',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='shop.family'),
        ),
    ]
